### ISSUE TITLE
Should require rack?

### ISSUE THREAD

**Issue by trevorturk** [nakajima/rip-server#1]
I'm not sure if this is a rip-server or rip issue, but...

$ rip install git://github.com/nakajima/rip-server.git
running install hook for sinatra
Successfully installed sinatra (3b992ad)
Successfully installed rip-server (864e87b)
~ $ rip server
/Users/trevorturk/.rip/active/lib/sinatra/base.rb:4:in `require': no such file to load -- rack (LoadError)

**Comment by trevorturk** [comment]
Also, now I can't get rip to do anything. I'm hunting for open issues like this in the rip issue list.

rip install git://github.com/rack/rack.git
/Users/trevorturk/.rip/active/lib/sinatra/base.rb:4:in `require': no such file to load -- rack (LoadError)

$ rip check
/Users/trevorturk/.rip/active/lib/sinatra/base.rb:4:in `require': no such file to load -- rack (LoadError)
